version: '3.8'

services:
  app:
    image: geocity-website:0.0.1
    environment:
      - PROJECT_NAME
      - DEPLOY_ENV
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PROJECT_NAME
    ports:
      - 8082:8000
    volumes:
      - ${DB_DATA}:/app/dbdata/
      - ${MEDIA_DIR}:/app/media/
    entrypoint: docker-entrypoint.sh

